---
- name: Benchmark facts (baseline)
  hosts: all
  gather_facts: no
  tags:
    - benchmark-facts-baseline
  tasks: 
    - name: Hello, world
      debug:
        msg: Hello, world

- import_playbook: ../gather-facts.yml

- name: Benchmark facts (with facts)
  hosts: all
  gather_facts: no
  tags:
    - benchmark-facts-with-facts
  tasks: 
    - name: Hello, world
      debug:
        msg: Hello, world

- import_playbook: ../group-hosts.yml

- name: Benchmark facts (with facts and dynamic groups)
  hosts: all
  gather_facts: no
  tags:
    - benchmark-facts-with-facts-and-groups
  tasks: 
    - name: Hello, world
      debug:
        msg: Hello, world
