---
- import_playbook: gather-facts.yml
  when: gather_facts | default(false) | bool

- import_playbook: group-hosts.yml
  when: group_hosts | default(false) | bool

- name: Benchmark task_include
  gather_facts: false
  hosts: all
  tags:
    - benchmark-task-include
  tasks:
    - import_role:
        name: benchmark-include-import
        tasks_from: task-include.yml

- name: Benchmark task_import
  gather_facts: false
  hosts: all
  tags:
    - benchmark-task-import
  tasks:
    - import_role:
        name: benchmark-include-import
        tasks_from: task-import.yml

- name: Benchmark skipped task_include
  gather_facts: false
  hosts: all
  tags:
    - benchmark-skipped-task-include
  tasks:
    - import_role:
        name: benchmark-include-import
        tasks_from: skipped-task-include.yml

- name: Benchmark skipped task_import
  gather_facts: false
  hosts: all
  tags:
    - benchmark-skipped-task-import
  tasks:
    - import_role:
        name: benchmark-include-import
        tasks_from: skipped-task-import.yml

- name: Benchmark task_include loop
  gather_facts: false
  hosts: all
  tags:
    - benchmark-task-include-loop
  tasks:
    - import_role:
        name: benchmark-include-import
        tasks_from: task-include-loop.yml

- name: Benchmark skipped task_include loop
  gather_facts: false
  hosts: all
  tags:
    - benchmark-skipped-task-include-loop
  tasks:
    - import_role:
        name: benchmark-include-import
        tasks_from: skipped-task-include-loop.yml

- name: Benchmark old role import
  gather_facts: false
  hosts: all
  tags:
    - benchmark-old-role-import
  vars:
    include_file: nested
  roles:
    - role: benchmark-include-import

- name: Benchmark new role import
  gather_facts: false
  hosts: all
  tags:
    - benchmark-new-role-import
  vars:
    include_file: nested
  tasks:
    - import_role:
        name: benchmark-include-import

- name: Benchmark role include with tasks_from
  gather_facts: false
  hosts: all
  tags:
    - benchmark-role-include-with-tasks-from
  vars:
    include_file: nested
  tasks:
    - name: include benchmark role with tasks_from
      include_role:
        name: benchmark-include-import
        tasks_from: "{{ include_file }}.yml"
