---
- import_playbook: gather-facts.yml
  when: gather_facts | default(false) | bool

- import_playbook: group-hosts.yml
  when: group_hosts | default(false) | bool

- name: Benchmark run once yes
  gather_facts: false
  hosts: all
  tags:
    - benchmark-run-once-yes
  tasks:
    - name: Debug
      debug:
        msg: Hello, world
      run_once: yes

- name: Benchmark run once no skipped
  gather_facts: false
  hosts: all
  tags:
    - benchmark-run-once-no-skipped
  tasks:
    - name: Debug
      debug:
        msg: Hello, world
      run_once: no
      when: inventory_hostname == groups['all'][0]
